pool:
  vmImage: ubuntu-latest

    - task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
    - task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'rcarozu-sonar'
    organization: 'rcarozu-devsecops'
    scannerMode: 'MSBuild'
    projectKey: 'rcarozu-DevSecOps_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'
