pool:
  vmImage: ubuntu-latest

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'rcarozu-sonar'
    organization: 'rcarozu-devsecops'
    scannerMode: 'MSBuild'
    projectKey: 'rcarozu-DevSecOps_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'
    

- task: dependency-check-build-task@6
  inputs:
    projectName: 'spring-boot-kubernetes'
    scanPath: '$(Build.ArtifactStagingDirectory)'
    format: 'HTML'